project:
  type: website

website:
  title: "Curso de SQL - Configuração Geral"
  navbar:
    left:
      - href: index.qmd
        text: Início

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3