project:
  type: website
  output-dir: docs

website:
  title: "Configuração do Ambiente"
  navbar:
    left:
      - href: index.qmd
        text: Início

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3